"""
grid_io.py — Import and export functions for the level grid.

Supports four formats:
  - JSON          (.json)  — native save/load format
  - ASCII         (.txt)   — human-readable char map
  - C++ setters            — loadLevel() function body for Arduino
  - Raw uint8_t array      — flat C array for direct memcpy on Arduino
"""

import json
import re
from typing import List, Optional

from models import Cell, BG, ENT, empty_grid
from constants import GRID_W, GRID_H


# ── JSON ─────────────────────────────────────────────────────────────────────

def grid_to_json_obj(grid: List[List[Cell]]) -> dict:
    """Serialise the grid to a plain Python dict (ready for json.dump)."""
    return {
        "width":  GRID_W,
        "height": GRID_H,
        "grid":   [[grid[x][y].data for y in range(GRID_H)] for x in range(GRID_W)],
    }


def grid_from_json_obj(obj: dict) -> List[List[Cell]]:
    """
    Deserialise a dict produced by grid_to_json_obj.
    Tolerates grids smaller than GRID_W × GRID_H (missing cells stay empty).
    """
    raw = obj["grid"]
    grid = empty_grid(GRID_W, GRID_H)
    for x in range(min(GRID_W, len(raw))):
        for y in range(min(GRID_H, len(raw[x]))):
            grid[x][y] = Cell(raw[x][y])
    return grid


def save_json(grid: List[List[Cell]], path: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(grid_to_json_obj(grid), fh)


def load_json(path: str) -> List[List[Cell]]:
    with open(path, encoding="utf-8") as fh:
        return grid_from_json_obj(json.load(fh))


# ── ASCII ─────────────────────────────────────────────────────────────────────

# Char → (BG, ENT) mapping used by both importer and exporter.
_CHAR_MAP: dict = {
    '#': (BG.WALL,     ENT.EMPTY),
    '.': (BG.GUM,      ENT.EMPTY),
    '*': (BG.ENERGIZE, ENT.EMPTY),
    ' ': (BG.EMPTY,    ENT.EMPTY),
    'P': (BG.EMPTY,    ENT.PACMAN),
    'R': (BG.EMPTY,    ENT.RED_GHOST),
    'B': (BG.EMPTY,    ENT.BLUE_GHOST),
    'K': (BG.EMPTY,    ENT.PINK_GHOST),
    'O': (BG.EMPTY,    ENT.ORANGE_GHOST),
    'F': (BG.EMPTY,    ENT.FRUIT),
}


def grid_to_ascii(grid: List[List[Cell]]) -> str:
    """Render the grid as a plain-text char map (y-first for readability)."""
    rows = []
    for y in range(GRID_H):
        rows.append("".join(grid[x][y].to_char() for x in range(GRID_W)))
    return "\n".join(rows)


def grid_from_ascii(text: str) -> Optional[List[List[Cell]]]:
    """
    Parse a char-map string into a Cell grid.
    Lines shorter than GRID_W are padded with spaces (empty cells).
    Returns None if the input is completely empty.
    """
    lines = text.split('\n')
    if not any(line.strip() for line in lines):
        return None
    # Pad to GRID_H rows
    while len(lines) < GRID_H:
        lines.append('')
    grid = empty_grid(GRID_W, GRID_H)
    for y, line in enumerate(lines[:GRID_H]):
        for x, ch in enumerate(line[:GRID_W]):
            if ch in _CHAR_MAP:
                bg, ent = _CHAR_MAP[ch]
                grid[x][y].set_bg(bg)
                grid[x][y].set_ent(ent)
    return grid


# ── C++ setters ───────────────────────────────────────────────────────────────

def grid_to_cpp(grid: List[List[Cell]]) -> str:
    """
    Generate a C++ loadLevel() function body that rebuilds the grid at runtime
    using setter calls — the same pattern expected by the Arduino game engine.
    """
    lines = [
        "// Level generated by Pac-Man Level Editor",
        f"// Size: {GRID_W}×{GRID_H}",
        "",
        "void loadLevel(char level) {",
        "    memset(state.grid, 0, sizeof(state.grid));",
        "",
    ]

    pacman_pos = None
    ghost_positions: dict = {
        ENT.BLUE_GHOST:   None,
        ENT.RED_GHOST:    None,
        ENT.PINK_GHOST:   None,
        ENT.ORANGE_GHOST: None,
    }

    for y in range(GRID_H):
        for x in range(GRID_W):
            cell = grid[x][y]
            if cell.data == 0:
                continue
            bg  = cell.get_bg()
            ent = cell.get_ent()
            if bg != BG.EMPTY:
                lines.append(
                    f"    this->state.grid[{x}][{y}]"
                    f".setBackground({_bg_cpp(bg)});"
                )
            if ent != ENT.EMPTY:
                lines.append(
                    f"    this->state.grid[{x}][{y}]"
                    f".setEntity({_ent_cpp(ent)});"
                )
                if ent == ENT.PACMAN:
                    pacman_pos = (x, y)
                elif ent in ghost_positions:
                    ghost_positions[ent] = (x, y)

    lines.append("")
    lines.append("    // Initial positions")

    if pacman_pos:
        lines.append(
            f"    this->pacmanPosition = {{{pacman_pos[0]}, {pacman_pos[1]}}};"
        )

    ghost_setters = {
        ENT.BLUE_GHOST:   "this->blueGhost.setPosition",
        ENT.RED_GHOST:    "this->redGhost.setPosition",
        ENT.PINK_GHOST:   "this->pinkGhost.setPosition",
        ENT.ORANGE_GHOST: "this->orangeGhost.setPosition",
    }
    for ent, setter in ghost_setters.items():
        pos = ghost_positions[ent]
        if pos:
            lines.append(f"    {setter}({{{pos[0]}, {pos[1]}}});")

    lines.append("}")
    return "\n".join(lines)


# ── Raw uint8_t array ─────────────────────────────────────────────────────────

def grid_to_raw_array(grid: List[List[Cell]]) -> str:
    """
    Emit the grid as a flat C uint8_t array.
    The Arduino loader reads it with a nested for(x) for(y) loop.
    """
    lines = [
        "// Level generated by Pac-Man Level Editor",
        f"// Size: {GRID_W}×{GRID_H} — indexed [x][y]",
        "",
        f"const uint8_t level_data[{GRID_W}][{GRID_H}] = {{",
    ]
    for x in range(GRID_W):
        row = ", ".join(f"0x{grid[x][y].data:02X}" for y in range(GRID_H))
        comma = "," if x < GRID_W - 1 else ""
        lines.append(f"    {{{row}}}{comma}  // x={x}")
    lines += [
        "};",
        "",
        "// To load:",
        "// for(int x=0;x<GAME_GRID_X_AXIS_LEN;x++)",
        "//   for(int y=0;y<GAME_GRID_Y_AXIS_LEN;y++)",
        "//     state.grid[x][y].data = level_data[x][y];",
    ]
    return "\n".join(lines)


def grid_from_raw_array(text: str) -> Optional[List[List[Cell]]]:
    """
    Parse a raw uint8_t array (hex or decimal literals) back into a Cell grid.
    Returns None if fewer than GRID_W × GRID_H values are found.
    """
    hex_vals = re.findall(r'0[xX][0-9a-fA-F]+|\d+', text)
    vals = [
        int(v, 16) if v.lower().startswith('0x') else int(v)
        for v in hex_vals
    ]
    if len(vals) < GRID_W * GRID_H:
        return None
    grid = empty_grid(GRID_W, GRID_H)
    idx = 0
    for x in range(GRID_W):
        for y in range(GRID_H):
            grid[x][y] = Cell(vals[idx])
            idx += 1
    return grid


# ── C++ name helpers (private) ────────────────────────────────────────────────

def _bg_cpp(bg: BG) -> str:
    return {
        BG.WALL:     "BG_WALL",
        BG.GUM:      "BG_GUM",
        BG.ENERGIZE: "BG_ENERGIZE",
        BG.EMPTY:    "BG_EMPTY",
    }[bg]


def _ent_cpp(ent: ENT) -> str:
    return {
        ENT.PACMAN:       "ENT_PACMAN",
        ENT.BLUE_GHOST:   "ENT_BLUE_GHOST",
        ENT.RED_GHOST:    "ENT_RED_GHOST",
        ENT.PINK_GHOST:   "ENT_PINK_GHOST",
        ENT.ORANGE_GHOST: "ENT_ORANGE_GHOST",
        ENT.FRUIT:        "ENT_FRUIT",
        ENT.EMPTY:        "ENT_EMPTY",
    }[ent]
